[versions]
kotlin = "1.5.31"
spring-boot = "2.5.6"
spring-dependencyManagement = "1.0.11.RELEASE"
resilience4j = "1.7.1"
chaosMonkey = "2.5.4"
lombok = "6.1.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-dependencyManagement" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

[libraries]
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test" }
project-reactor-test = { module = "io.projectreactor:reactor-test" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
h2 = { module = "com.h2database:h2" }
resilience4j = { module = "io.github.resilience4j:resilience4j-core", version.ref = "resilience4j" }
chaosMonkey = { module = "de.codecentric:chaos-monkey-spring-boot", version.ref = "chaosMonkey" }

[bundles]
spring-boot-webflux = ["spring-boot-webflux","jackson-kotlin", "kotlin-reflect",  "kotlinx-coroutines-reactor"]